# Generated by Django 5.2.7 on 2025-11-13 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceDistrictModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "division",
                    models.CharField(
                        choices=[
                            ("Dhaka", "Dhaka"),
                            ("Chattogram", "Chattogram"),
                            ("Sylhet", "Sylhet"),
                            ("Khulna", "Khulna"),
                            ("Barishal", "Barishal"),
                            ("Rajshahi", "Rajshahi"),
                            ("Rangpur", "Rangpur"),
                            ("Mymensingh", "Mymensingh"),
                        ],
                        max_length=50,
                    ),
                ),
                ("districtName", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "responsiblePerson",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsible_person",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Service District",
                "verbose_name_plural": "Service Districts",
                "db_table": "ServiceDistrictModel",
            },
        ),
    ]
