[pytest]
DJANGO_SETTINGS_MODULE = bus_ticket_project.settings
python_files = *_test.py test_*.py
python_classes = *Test
python_functions = test_*
DJANGO_AUTO_REUSE_DB = true
django_db_setup = True