# Generated by Django 5.2.7 on 2025-11-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Staff", "Staff"),
                    ("Passenger", "Passenger"),
                ],
                default="passenger",
                max_length=20,
                null=True,
            ),
        ),
    ]
