# Generated by Django 5.2.7 on 2025-11-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Staff", "Staff"),
                    ("Passenger", "Passenger"),
                ],
                default="Passenger",
                max_length=20,
                null=True,
            ),
        ),
    ]
